export const ROUTES = {
  HOME: '/',
  COURS: '/cours',
  REGISTRATION: '/auth/registration',
  LOGIN: '/auth/login',
  ACCOUNT: '/account',
  LIST_MY_COURS: '/my-cours',
  BACKEND: '/cours/backend',
  FRONTEND: '/cours/frontend',
  SINGLE_MY_COURS: '/single-my-cours',
  SINGLE_MY_COURS_TASK: '/single-my-cours-task',
  SINGLE_MY_COURS_TASKS: '/single-my-cours-tasks/details',
  SINGLE_QUESTION: '/single-question',
  REDIRECT: '*',
  ADMIN: '/admin',
  RESET_PASSWORD: '/auth/reset-password',
  RESET_PASSWORD_REQUEST: '/auth/reset-password-request',
  COURSES_ADMIN: '/admin/courses',
  MODULES_ADMIN: '/admin/cours-modules',
  CHANGE_COURS: '/admin/cours',
  CREATE_COURS: '/admin/create-cours',
  CREATE_MODULE: '/admin/create-module',
  CHANGE_MODULE: '/admin/module',
};

export const BaseURL = 'http://localhost:5000';
