export const ROUTES = {
  HOME: '/',
  COURS: '/cours',
  REGISTRATION: '/auth/registration',
  LOGIN: '/auth/login',
  ACCOUNT: '/student/dashboard',
  LIST_MY_COURS: '/student/courses',
  BACKEND: '/cours/backend',
  FRONTEND: '/cours/frontend',
  SINGLE_MY_COURS: '/student/course',
  SINGLE_MY_COURS_TASK: '/student/module',
  SINGLE_MY_COURS_TASKS: '/student/lesson',
  SINGLE_QUESTION: '/student/single-question',
  REDIRECT: '*',
  ADMIN: '/admin',
  RESET_PASSWORD: '/auth/reset-password',
  RESET_PASSWORD_REQUEST: '/auth/reset-password-request',
  COURSES_ADMIN: '/admin/courses',
  MODULES_ADMIN: '/admin/cours-modules',
  CHANGE_COURS: '/admin/cours',
  CREATE_COURS: '/admin/create-cours',
  CREATE_MODULE: '/admin/create-module',
  CREATE_LESSON: '/admin/create-lesson',
  CHANGE_MODULE: '/admin/module',
  LESSONS_MODULE_ADMIN: '/admin/module-lessons',
};

export const BaseURL = 'http://localhost:5000';
